version: '3'

services:
  mysql:
    image: mysql:8.0
    container_name: auth-mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: auth_db
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - auth-network
      
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: auth-phpmyadmin
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      MYSQL_ROOT_PASSWORD: password
    ports:
      - "8081:80"
    depends_on:
      - mysql
    networks:
      - auth-network

networks:
  auth-network:
    driver: bridge

volumes:
  mysql-data: 